// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.9.2
// source: services.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0}
}

type Agent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
}

func (x *Agent) Reset() {
	*x = Agent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{1}
}

func (x *Agent) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Agent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Agent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Departemant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Agents   []*Agent `protobuf:"bytes,3,rep,name=Agents,proto3" json:"Agents,omitempty"`
}

func (x *Departemant) Reset() {
	*x = Departemant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Departemant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Departemant) ProtoMessage() {}

func (x *Departemant) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Departemant.ProtoReflect.Descriptor instead.
func (*Departemant) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{2}
}

func (x *Departemant) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Departemant) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Departemant) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type Agents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agents []*Agent `protobuf:"bytes,1,rep,name=Agents,proto3" json:"Agents,omitempty"`
}

func (x *Agents) Reset() {
	*x = Agents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Agents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agents) ProtoMessage() {}

func (x *Agents) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agents.ProtoReflect.Descriptor instead.
func (*Agents) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{3}
}

func (x *Agents) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type Departemants struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Departemants []*Departemant `protobuf:"bytes,1,rep,name=Departemants,proto3" json:"Departemants,omitempty"`
}

func (x *Departemants) Reset() {
	*x = Departemants{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Departemants) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Departemants) ProtoMessage() {}

func (x *Departemants) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Departemants.ProtoReflect.Descriptor instead.
func (*Departemants) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{4}
}

func (x *Departemants) GetDepartemants() []*Departemant {
	if x != nil {
		return x.Departemants
	}
	return nil
}

type Nofitication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info string `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
}

func (x *Nofitication) Reset() {
	*x = Nofitication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nofitication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nofitication) ProtoMessage() {}

func (x *Nofitication) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nofitication.ProtoReflect.Descriptor instead.
func (*Nofitication) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{5}
}

func (x *Nofitication) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type DepartemantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
}

func (x *DepartemantRequest) Reset() {
	*x = DepartemantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepartemantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartemantRequest) ProtoMessage() {}

func (x *DepartemantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartemantRequest.ProtoReflect.Descriptor instead.
func (*DepartemantRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{6}
}

func (x *DepartemantRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type DepartemantUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username        string       `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	DepartemantInfo *Departemant `protobuf:"bytes,2,opt,name=DepartemantInfo,proto3" json:"DepartemantInfo,omitempty"`
}

func (x *DepartemantUpdateRequest) Reset() {
	*x = DepartemantUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepartemantUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartemantUpdateRequest) ProtoMessage() {}

func (x *DepartemantUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartemantUpdateRequest.ProtoReflect.Descriptor instead.
func (*DepartemantUpdateRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{7}
}

func (x *DepartemantUpdateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DepartemantUpdateRequest) GetDepartemantInfo() *Departemant {
	if x != nil {
		return x.DepartemantInfo
	}
	return nil
}

type AgentUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifiers string `protobuf:"bytes,1,opt,name=Identifiers,proto3" json:"Identifiers,omitempty"`
	AgentInfo   *Agent `protobuf:"bytes,2,opt,name=AgentInfo,proto3" json:"AgentInfo,omitempty"`
}

func (x *AgentUpdateRequest) Reset() {
	*x = AgentUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUpdateRequest) ProtoMessage() {}

func (x *AgentUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUpdateRequest.ProtoReflect.Descriptor instead.
func (*AgentUpdateRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{8}
}

func (x *AgentUpdateRequest) GetIdentifiers() string {
	if x != nil {
		return x.Identifiers
	}
	return ""
}

func (x *AgentUpdateRequest) GetAgentInfo() *Agent {
	if x != nil {
		return x.AgentInfo
	}
	return nil
}

type AgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifiers string `protobuf:"bytes,1,opt,name=Identifiers,proto3" json:"Identifiers,omitempty"`
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{9}
}

func (x *AgentRequest) GetIdentifiers() string {
	if x != nil {
		return x.Identifiers
	}
	return ""
}

var File_services_proto protoreflect.FileDescriptor

var file_services_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x49, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x5f, 0x0a, 0x0b, 0x44,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x2e, 0x0a, 0x06,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x46, 0x0a, 0x0c,
	0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x36, 0x0a, 0x0c,
	0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x52, 0x0c, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d,
	0x61, 0x6e, 0x74, 0x73, 0x22, 0x22, 0x0a, 0x0c, 0x4e, 0x6f, 0x66, 0x69, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x30, 0x0a, 0x12, 0x44, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x74, 0x0a, 0x18, 0x44, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x0f, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x61, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x52,
	0x0f, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x62, 0x0a, 0x12, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x12, 0x2a, 0x0a, 0x09, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x30, 0x0a, 0x0c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x32, 0xe1, 0x04, 0x0a, 0x12, 0x44, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x61,
	0x6e, 0x74, 0x73, 0x12, 0x45, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x0e, 0x41, 0x64,
	0x64, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x61, 0x6e, 0x74,
	0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x66, 0x69, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x48, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x12,
	0x43, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x66, 0x69, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x3a,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x41, 0x64,
	0x64, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x66,
	0x69, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x0b, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x12, 0x37, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f,
	0x66, 0x69, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_services_proto_rawDescOnce sync.Once
	file_services_proto_rawDescData = file_services_proto_rawDesc
)

func file_services_proto_rawDescGZIP() []byte {
	file_services_proto_rawDescOnce.Do(func() {
		file_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_proto_rawDescData)
	})
	return file_services_proto_rawDescData
}

var file_services_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_services_proto_goTypes = []interface{}{
	(*Empty)(nil),                    // 0: proto.Empty
	(*Agent)(nil),                    // 1: proto.Agent
	(*Departemant)(nil),              // 2: proto.Departemant
	(*Agents)(nil),                   // 3: proto.Agents
	(*Departemants)(nil),             // 4: proto.Departemants
	(*Nofitication)(nil),             // 5: proto.Nofitication
	(*DepartemantRequest)(nil),       // 6: proto.DepartemantRequest
	(*DepartemantUpdateRequest)(nil), // 7: proto.DepartemantUpdateRequest
	(*AgentUpdateRequest)(nil),       // 8: proto.AgentUpdateRequest
	(*AgentRequest)(nil),             // 9: proto.AgentRequest
}
var file_services_proto_depIdxs = []int32{
	1,  // 0: proto.Departemant.Agents:type_name -> proto.Agent
	1,  // 1: proto.Agents.Agents:type_name -> proto.Agent
	2,  // 2: proto.Departemants.Departemants:type_name -> proto.Departemant
	2,  // 3: proto.DepartemantUpdateRequest.DepartemantInfo:type_name -> proto.Departemant
	1,  // 4: proto.AgentUpdateRequest.AgentInfo:type_name -> proto.Agent
	0,  // 5: proto.DepartemantService.GetDepartements:input_type -> proto.Empty
	6,  // 6: proto.DepartemantService.GetDepartementByName:input_type -> proto.DepartemantRequest
	2,  // 7: proto.DepartemantService.AddDepartement:input_type -> proto.Departemant
	7,  // 8: proto.DepartemantService.UpdateDepartement:input_type -> proto.DepartemantUpdateRequest
	6,  // 9: proto.DepartemantService.DeleteDepartement:input_type -> proto.DepartemantRequest
	0,  // 10: proto.DepartemantService.GetAgents:input_type -> proto.Empty
	9,  // 11: proto.DepartemantService.GetAgentByIdentifiers:input_type -> proto.AgentRequest
	1,  // 12: proto.DepartemantService.AddAgent:input_type -> proto.Agent
	8,  // 13: proto.DepartemantService.UpdateAgent:input_type -> proto.AgentUpdateRequest
	9,  // 14: proto.DepartemantService.DeleteAgent:input_type -> proto.AgentRequest
	4,  // 15: proto.DepartemantService.GetDepartements:output_type -> proto.Departemants
	2,  // 16: proto.DepartemantService.GetDepartementByName:output_type -> proto.Departemant
	5,  // 17: proto.DepartemantService.AddDepartement:output_type -> proto.Nofitication
	2,  // 18: proto.DepartemantService.UpdateDepartement:output_type -> proto.Departemant
	5,  // 19: proto.DepartemantService.DeleteDepartement:output_type -> proto.Nofitication
	3,  // 20: proto.DepartemantService.GetAgents:output_type -> proto.Agents
	1,  // 21: proto.DepartemantService.GetAgentByIdentifiers:output_type -> proto.Agent
	5,  // 22: proto.DepartemantService.AddAgent:output_type -> proto.Nofitication
	1,  // 23: proto.DepartemantService.UpdateAgent:output_type -> proto.Agent
	5,  // 24: proto.DepartemantService.DeleteAgent:output_type -> proto.Nofitication
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_services_proto_init() }
func file_services_proto_init() {
	if File_services_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Agent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Departemant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Agents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Departemants); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nofitication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepartemantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepartemantUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_proto_goTypes,
		DependencyIndexes: file_services_proto_depIdxs,
		MessageInfos:      file_services_proto_msgTypes,
	}.Build()
	File_services_proto = out.File
	file_services_proto_rawDesc = nil
	file_services_proto_goTypes = nil
	file_services_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DepartemantServiceClient is the client API for DepartemantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DepartemantServiceClient interface {
	GetDepartements(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Departemants, error)
	GetDepartementByName(ctx context.Context, in *DepartemantRequest, opts ...grpc.CallOption) (*Departemant, error)
	AddDepartement(ctx context.Context, in *Departemant, opts ...grpc.CallOption) (*Nofitication, error)
	UpdateDepartement(ctx context.Context, in *DepartemantUpdateRequest, opts ...grpc.CallOption) (*Departemant, error)
	DeleteDepartement(ctx context.Context, in *DepartemantRequest, opts ...grpc.CallOption) (*Nofitication, error)
	GetAgents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Agents, error)
	GetAgentByIdentifiers(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (*Agent, error)
	AddAgent(ctx context.Context, in *Agent, opts ...grpc.CallOption) (*Nofitication, error)
	UpdateAgent(ctx context.Context, in *AgentUpdateRequest, opts ...grpc.CallOption) (*Agent, error)
	DeleteAgent(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (*Nofitication, error)
}

type departemantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDepartemantServiceClient(cc grpc.ClientConnInterface) DepartemantServiceClient {
	return &departemantServiceClient{cc}
}

func (c *departemantServiceClient) GetDepartements(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Departemants, error) {
	out := new(Departemants)
	err := c.cc.Invoke(ctx, "/proto.DepartemantService/GetDepartements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departemantServiceClient) GetDepartementByName(ctx context.Context, in *DepartemantRequest, opts ...grpc.CallOption) (*Departemant, error) {
	out := new(Departemant)
	err := c.cc.Invoke(ctx, "/proto.DepartemantService/GetDepartementByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departemantServiceClient) AddDepartement(ctx context.Context, in *Departemant, opts ...grpc.CallOption) (*Nofitication, error) {
	out := new(Nofitication)
	err := c.cc.Invoke(ctx, "/proto.DepartemantService/AddDepartement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departemantServiceClient) UpdateDepartement(ctx context.Context, in *DepartemantUpdateRequest, opts ...grpc.CallOption) (*Departemant, error) {
	out := new(Departemant)
	err := c.cc.Invoke(ctx, "/proto.DepartemantService/UpdateDepartement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departemantServiceClient) DeleteDepartement(ctx context.Context, in *DepartemantRequest, opts ...grpc.CallOption) (*Nofitication, error) {
	out := new(Nofitication)
	err := c.cc.Invoke(ctx, "/proto.DepartemantService/DeleteDepartement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departemantServiceClient) GetAgents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Agents, error) {
	out := new(Agents)
	err := c.cc.Invoke(ctx, "/proto.DepartemantService/GetAgents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departemantServiceClient) GetAgentByIdentifiers(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, "/proto.DepartemantService/GetAgentByIdentifiers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departemantServiceClient) AddAgent(ctx context.Context, in *Agent, opts ...grpc.CallOption) (*Nofitication, error) {
	out := new(Nofitication)
	err := c.cc.Invoke(ctx, "/proto.DepartemantService/AddAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departemantServiceClient) UpdateAgent(ctx context.Context, in *AgentUpdateRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, "/proto.DepartemantService/UpdateAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *departemantServiceClient) DeleteAgent(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (*Nofitication, error) {
	out := new(Nofitication)
	err := c.cc.Invoke(ctx, "/proto.DepartemantService/DeleteAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepartemantServiceServer is the server API for DepartemantService service.
type DepartemantServiceServer interface {
	GetDepartements(context.Context, *Empty) (*Departemants, error)
	GetDepartementByName(context.Context, *DepartemantRequest) (*Departemant, error)
	AddDepartement(context.Context, *Departemant) (*Nofitication, error)
	UpdateDepartement(context.Context, *DepartemantUpdateRequest) (*Departemant, error)
	DeleteDepartement(context.Context, *DepartemantRequest) (*Nofitication, error)
	GetAgents(context.Context, *Empty) (*Agents, error)
	GetAgentByIdentifiers(context.Context, *AgentRequest) (*Agent, error)
	AddAgent(context.Context, *Agent) (*Nofitication, error)
	UpdateAgent(context.Context, *AgentUpdateRequest) (*Agent, error)
	DeleteAgent(context.Context, *AgentRequest) (*Nofitication, error)
}

// UnimplementedDepartemantServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDepartemantServiceServer struct {
}

func (*UnimplementedDepartemantServiceServer) GetDepartements(context.Context, *Empty) (*Departemants, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartements not implemented")
}
func (*UnimplementedDepartemantServiceServer) GetDepartementByName(context.Context, *DepartemantRequest) (*Departemant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepartementByName not implemented")
}
func (*UnimplementedDepartemantServiceServer) AddDepartement(context.Context, *Departemant) (*Nofitication, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDepartement not implemented")
}
func (*UnimplementedDepartemantServiceServer) UpdateDepartement(context.Context, *DepartemantUpdateRequest) (*Departemant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDepartement not implemented")
}
func (*UnimplementedDepartemantServiceServer) DeleteDepartement(context.Context, *DepartemantRequest) (*Nofitication, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDepartement not implemented")
}
func (*UnimplementedDepartemantServiceServer) GetAgents(context.Context, *Empty) (*Agents, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgents not implemented")
}
func (*UnimplementedDepartemantServiceServer) GetAgentByIdentifiers(context.Context, *AgentRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentByIdentifiers not implemented")
}
func (*UnimplementedDepartemantServiceServer) AddAgent(context.Context, *Agent) (*Nofitication, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAgent not implemented")
}
func (*UnimplementedDepartemantServiceServer) UpdateAgent(context.Context, *AgentUpdateRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgent not implemented")
}
func (*UnimplementedDepartemantServiceServer) DeleteAgent(context.Context, *AgentRequest) (*Nofitication, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAgent not implemented")
}

func RegisterDepartemantServiceServer(s *grpc.Server, srv DepartemantServiceServer) {
	s.RegisterService(&_DepartemantService_serviceDesc, srv)
}

func _DepartemantService_GetDepartements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartemantServiceServer).GetDepartements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DepartemantService/GetDepartements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartemantServiceServer).GetDepartements(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartemantService_GetDepartementByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartemantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartemantServiceServer).GetDepartementByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DepartemantService/GetDepartementByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartemantServiceServer).GetDepartementByName(ctx, req.(*DepartemantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartemantService_AddDepartement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Departemant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartemantServiceServer).AddDepartement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DepartemantService/AddDepartement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartemantServiceServer).AddDepartement(ctx, req.(*Departemant))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartemantService_UpdateDepartement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartemantUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartemantServiceServer).UpdateDepartement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DepartemantService/UpdateDepartement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartemantServiceServer).UpdateDepartement(ctx, req.(*DepartemantUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartemantService_DeleteDepartement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepartemantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartemantServiceServer).DeleteDepartement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DepartemantService/DeleteDepartement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartemantServiceServer).DeleteDepartement(ctx, req.(*DepartemantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartemantService_GetAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartemantServiceServer).GetAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DepartemantService/GetAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartemantServiceServer).GetAgents(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartemantService_GetAgentByIdentifiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartemantServiceServer).GetAgentByIdentifiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DepartemantService/GetAgentByIdentifiers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartemantServiceServer).GetAgentByIdentifiers(ctx, req.(*AgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartemantService_AddAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Agent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartemantServiceServer).AddAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DepartemantService/AddAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartemantServiceServer).AddAgent(ctx, req.(*Agent))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartemantService_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartemantServiceServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DepartemantService/UpdateAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartemantServiceServer).UpdateAgent(ctx, req.(*AgentUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepartemantService_DeleteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepartemantServiceServer).DeleteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DepartemantService/DeleteAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepartemantServiceServer).DeleteAgent(ctx, req.(*AgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DepartemantService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DepartemantService",
	HandlerType: (*DepartemantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDepartements",
			Handler:    _DepartemantService_GetDepartements_Handler,
		},
		{
			MethodName: "GetDepartementByName",
			Handler:    _DepartemantService_GetDepartementByName_Handler,
		},
		{
			MethodName: "AddDepartement",
			Handler:    _DepartemantService_AddDepartement_Handler,
		},
		{
			MethodName: "UpdateDepartement",
			Handler:    _DepartemantService_UpdateDepartement_Handler,
		},
		{
			MethodName: "DeleteDepartement",
			Handler:    _DepartemantService_DeleteDepartement_Handler,
		},
		{
			MethodName: "GetAgents",
			Handler:    _DepartemantService_GetAgents_Handler,
		},
		{
			MethodName: "GetAgentByIdentifiers",
			Handler:    _DepartemantService_GetAgentByIdentifiers_Handler,
		},
		{
			MethodName: "AddAgent",
			Handler:    _DepartemantService_AddAgent_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _DepartemantService_UpdateAgent_Handler,
		},
		{
			MethodName: "DeleteAgent",
			Handler:    _DepartemantService_DeleteAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
